---
# Include variables and define neeeded variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include: "setup-{{ ansible_distribution }}.yml"
  static: no

- name: Ensure Docker has started and enabled on boot
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes
